### test lambda locally
POST http://2f6jlllegr3ctfir0y3c4801ubak06du.lambda-url.us-east-1.localhost.localstack.cloud:4566 HTTP/1.1
Content-Type: application/json

{
    "num1": "10", 
    "num2": "10"
}

### test lambda 
POST http://p8hxbii8tydgr0jcv4pu4rr1kl90703f.lambda-url.us-east-1.localhost.localstack.cloud:4566/ HTTP/1.1
Content-Type: application/json
{
    
}